spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    username: root
    password: 181315durwo
  sql:
    init:
      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    defer-datasource-initialization: true
  main:
    allow-circular-references: true

server:
  port: 8050

app:
  default:
    password: topsecret
