spring:
  config:
    import: file:env.properties
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://${MYSQL_HOST:localhost:}3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS}
  sql:
    init:
      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    defer-datasource-initialization: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: danidavidov13.dd@gmail.com
    password: ${MAIL_PASS}

server:
  port: 8050


